# Generated by Django 5.2.5 on 2025-08-28 17:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_back',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='mentor_id'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id_front',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='mentor_id'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='mentor_images/'),
        ),
    ]
