# Generated by Django 5.2.5 on 2025-08-28 18:23

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_teacher_id_back_alter_teacher_id_front_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='city',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_front',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('verfied', 'Verified'), ('in_progress', 'In Progress'), ('unverfied', 'Unverfied')], default='unverfied', max_length=20),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='mentor_images/')),
                ('id_front', cloudinary.models.CloudinaryField(max_length=255, verbose_name='mentor_id')),
                ('id_back', cloudinary.models.CloudinaryField(max_length=255, verbose_name='mentor_id')),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='account.teacher')),
            ],
        ),
    ]
