# Generated by Django 5.2.5 on 2025-09-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_student'),
        ('controlpanel', '0002_sport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='coach_type',
            field=models.ManyToManyField(blank=True, related_name='teacher', to='controlpanel.sport'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
