# Generated by Django 5.2.5 on 2025-09-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_teacher_coach_type_teacher_institute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_type',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('pro', 'Pro Plan')], default='basic', max_length=12),
        ),
    ]
