# Generated by Django 5.2.5 on 2025-09-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='if_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
