# Generated by Django 5.2.5 on 2025-09-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_teacher_if_profile_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='if_profile_complete',
            new_name='is_profile_complete',
        ),
    ]
