# Generated by Django 5.2.5 on 2025-09-17 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_teacher_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='account.teacher'),
        ),
    ]
