# Generated by Django 5.2.5 on 2025-09-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_document_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('verfied', 'Verified'), ('in_progress', 'In Progress'), ('unverfied', 'Unverfied'), ('reject', 'Reject')], default='unverfied', max_length=20),
        ),
    ]
