# Generated by Django 5.2.5 on 2025-10-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_student_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('verified', 'Verified'), ('in_progress', 'In Progress'), ('unverfied', 'Unverfied'), ('reject', 'Reject')], default='not_submitted', max_length=20),
        ),
    ]
