# Generated by Django 5.2.5 on 2025-10-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='account_type',
            field=models.CharField(choices=[('basic', 'Basic Plan'), ('pro', 'Pro Plan')], default='basic', max_length=12),
        ),
    ]
