# Generated by Django 5.2.5 on 2025-10-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_teacher_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='can_access_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
