# Generated by Django 5.2.5 on 2025-09-02 00:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
