# Generated by Django 5.2.5 on 2025-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='public_id',
            field=models.CharField(max_length=255),
        ),
    ]
