# Generated by Django 5.2.5 on 2025-08-23 00:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_number', models.CharField(max_length=50, unique=True)),
                ('topic', models.CharField(default='Consultation', max_length=255)),
                ('start_url', models.URLField()),
                ('join_url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
