# Generated by Django 5.2.5 on 2025-08-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_alter_consultationmeeting_meeting_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationmeeting',
            name='meeting_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
