# Generated by Django 5.2.5 on 2025-09-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_conversation_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
