# Generated by Django 5.2.7 on 2025-10-02 22:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3c1e01b8-ed27-4714-97c9-67d8b9e94f00'), editable=False, primary_key=True, serialize=False),
        ),
    ]
