# Generated by Django 5.2.5 on 2025-09-27 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8e59e3d-4b9a-440a-b234-887f59fe0aff'), editable=False, primary_key=True, serialize=False),
        ),
    ]
