# Generated by Django 5.2.5 on 2025-10-07 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3786dbda-1180-422a-823d-3c3d928286d0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
