# Generated by Django 5.2.5 on 2025-10-07 23:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac66d975-b852-465c-acbd-120f3b7b0b0f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
