# Generated by Django 5.2.5 on 2025-10-10 23:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8cf7d24c-9a92-4fc0-b502-e52205f20468'), editable=False, primary_key=True, serialize=False),
        ),
    ]
