# Generated by Django 5.2.5 on 2025-10-11 20:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95100087-4e23-470a-a918-50e280972b1d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
