# Generated by Django 5.2.5 on 2025-10-12 09:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e2a821b-f936-4707-a068-24b4fb37a5af'), editable=False, primary_key=True, serialize=False),
        ),
    ]
