# Generated by Django 5.2.5 on 2025-10-17 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('def878bb-421d-4a08-91e0-35a9d6c62627'), editable=False, primary_key=True, serialize=False),
        ),
    ]
