# Generated by Django 5.2.5 on 2025-10-17 19:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fe6d2837-d2b6-4390-a754-4324c36bb132'), editable=False, primary_key=True, serialize=False),
        ),
    ]
