# Generated by Django 5.2.5 on 2025-10-17 19:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1b6a9f1f-122f-4c8f-b276-95e8a3b6d3c3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
