# Generated by Django 5.2.5 on 2025-10-17 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_studentsubscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9eba4780-2e01-408a-af0c-1177f0c14d09'), editable=False, primary_key=True, serialize=False),
        ),
    ]
