# Generated by Django 5.2.5 on 2025-08-29 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_remove_teacher_city_remove_teacher_id_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDays',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availabledays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabledays', to='teacher.availabledays')),
            ],
        ),
        migrations.CreateModel(
            name='SessionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('training_type', models.CharField(choices=[('virtual', 'Virtual Training'), ('mindset', 'Mindset Training'), ('in_person', 'In Person Training')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('close_before', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='account.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='availabledays',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabledays', to='teacher.sessionoption'),
        ),
    ]
