# Generated by Django 5.2.5 on 2025-09-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='channel_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
