# Generated by Django 5.2.5 on 2025-08-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableDays',
            new_name='AvailableDay',
        ),
    ]
