# Generated by Django 5.2.5 on 2025-09-12 22:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_if_profile_complete_teacher_is_profile_complete'),
        ('teacher', '0002_bookedsession_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_paid_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_reservation', models.PositiveIntegerField(default=0)),
                ('occupied_sits', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='VisitCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visit_count', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_counts', to='teacher.dashboard')),
            ],
        ),
    ]
