# Generated by Django 5.2.5 on 2025-09-02 18:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_teacher_coach_type_teacher_institute_name'),
        ('teacher', '0002_rename_availabledays_availableday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField(default=60)),
                ('is_paid', models.BooleanField(default=False)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_sessions', to='teacher.sessionoption')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_sessions_as_student', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_sessions_as_teacher', to='account.teacher')),
            ],
        ),
    ]
