# Generated by Django 5.2.5 on 2025-09-13 00:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_if_profile_complete_teacher_is_profile_complete'),
        ('teacher', '0003_dashboard_visitcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('after_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_history', to='account.teacher')),
            ],
        ),
    ]
