# Generated by Django 5.2.5 on 2025-09-13 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_incomehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
