# Generated by Django 5.2.5 on 2025-09-13 23:58

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_if_profile_complete_teacher_is_profile_complete'),
        ('teacher', '0006_alter_incomehistory_deduction_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_acc_num', models.CharField(max_length=50)),
                ('bank_routing_num', models.CharField(max_length=50)),
                ('account_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_accounts', to='account.teacher')),
            ],
        ),
    ]
