# Generated by Django 5.2.5 on 2025-09-14 00:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_if_profile_complete_teacher_is_profile_complete'),
        ('teacher', '0007_bank_paypal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='bank',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='account.teacher'),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_accounts', to='account.teacher'),
        ),
    ]
