# Generated by Django 5.2.5 on 2025-09-16 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_if_profile_complete_teacher_is_profile_complete'),
        ('teacher', '0008_alter_bank_account_type_alter_bank_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_video', to='account.teacher')),
            ],
        ),
    ]
