# Generated by Django 5.2.5 on 2025-10-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_accountvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
