# Generated by Django 5.2.5 on 2025-10-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_alter_ratingreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
