# Generated by Django 5.2.5 on 2025-10-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_teacher_status'),
        ('teacher', '0011_bookedsession_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingreview',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_ratings', to='account.student'),
        ),
        migrations.AlterField(
            model_name='ratingreview',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to='account.teacher'),
        ),
    ]
