# Generated by Django 5.2.5 on 2025-10-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_alter_ratingreview_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedsession',
            name='notification_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
