# Generated by Django 5.2.5 on 2025-08-31 23:30

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='admin/'),
            preserve_default=False,
        ),
    ]
