# Generated by Django 5.2.5 on 2025-09-05 00:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0002_sport_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('all_time_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('all_time_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('all_time_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('subscription_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('consultancy_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_coach', models.PositiveIntegerField(default=0)),
                ('total_student', models.PositiveIntegerField(default=0)),
                ('current_month_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_month_expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_month_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('current_month_newuser', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionBreakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('virtual_count', models.IntegerField(default=0)),
                ('virtual_increment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('mindset_count', models.IntegerField(default=0)),
                ('mindset_increment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('inperson_count', models.IntegerField(default=0)),
                ('inperson_increment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_breakdowns', to='controlpanel.statistic')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='controlpanel.statistic')),
            ],
            options={
                'unique_together': {('statistic', 'year', 'month')},
            },
        ),
    ]
