# Generated by Django 5.2.5 on 2025-09-13 00:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0003_statistic_sessionbreakdown_monthlystatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
                ('second_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
            ],
        ),
    ]
