# Generated by Django 5.2.5 on 2025-09-13 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0004_teacherdeduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdeduction',
            name='first_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
        migrations.AlterField(
            model_name='teacherdeduction',
            name='second_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.99)]),
        ),
    ]
