# Generated by Django 5.2.5 on 2025-09-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0005_alter_teacherdeduction_first_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdeduction',
            name='first_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='teacherdeduction',
            name='second_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
