# Generated by Django 5.2.5 on 2025-09-13 00:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0006_alter_teacherdeduction_first_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdeduction',
            name='first_time',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='teacherdeduction',
            name='second_time',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddConstraint(
            model_name='teacherdeduction',
            constraint=models.CheckConstraint(condition=models.Q(('first_time__gt', models.F('second_time'))), name='first_time_gt_second_time'),
        ),
    ]
