# Generated by Django 5.2.5 on 2025-09-13 18:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0007_alter_teacherdeduction_first_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminIncome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('after_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deduction_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=2)),
            ],
        ),
    ]
