# Generated by Django 5.2.5 on 2025-09-13 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0008_adminincome'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminincome',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
