# Generated by Django 5.2.5 on 2025-09-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0009_adminincome_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminincome',
            name='deduction_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
