# Generated by Django 5.2.5 on 2025-09-15 17:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_if_profile_complete_teacher_is_profile_complete'),
        ('controlpanel', '0010_alter_adminincome_deduction_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet_type', models.CharField(choices=[('Bank', 'Bank'), ('PayPal', 'PayPal')], max_length=8)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('left_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='account.teacher')),
            ],
        ),
    ]
