# Generated by Django 5.2.5 on 2025-09-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0011_withdraw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='wallet_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('paypal', 'PayPal')], max_length=8),
        ),
    ]
