# Generated by Django 5.2.5 on 2025-09-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0012_alter_withdraw_wallet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Accept', 'accept'), ('Reject', 'reject')], default='pending', max_length=8),
        ),
    ]
