# Generated by Django 5.2.5 on 2025-09-24 19:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0013_withdraw_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('public_id', models.CharField(max_length=255)),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'processing'), ('ready', 'ready'), ('failed', 'failed')], default='processing', max_length=20)),
                ('consumer', models.CharField(choices=[('Student', 'student'), ('Teacher', 'teacher')], default='student', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
