# Generated by Django 5.2.5 on 2025-09-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0014_adminvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminvideo',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
