# Generated by Django 5.2.5 on 2025-09-24 19:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0015_adminvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminvideo',
            name='thumbnail',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
