# Generated by Django 5.2.5 on 2025-09-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0016_alter_adminvideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminvideo',
            name='consumer',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher')], default='student', max_length=12),
        ),
    ]
