# Generated by Django 5.2.5 on 2025-09-24 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlpanel', '0017_alter_adminvideo_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminvideo',
            name='sport',
            field=models.ForeignKey(default='588a0b64-0aab-4b03-970c-e577e4764977', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='controlpanel.sport'),
            preserve_default=False,
        ),
    ]
